export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  size?: string;
  createdTime?: string;
  modifiedTime?: string;
  thumbnailLink?: string;
  webViewLink?: string;
  webContentLink?: string;
  description?: string;
  properties?: Record<string, string>;
  iconLink?: string;
}

export interface DriveStorageQuota {
  limit?: string;
  usage?: string;
  usageInDrive?: string;
  usageInDriveTrash?: string;
  userName?: string;
  userEmail?: string;
  userPhoto?: string;
}

const CHRONO_FOLDER_NAME = 'Chrono-Lens Temporal Archives';

/**
 * Find or create the Chrono-Lens folder in the user's Google Drive root.
 */
export async function findOrCreateChronoFolder(accessToken: string): Promise<string> {
  // Check if folder already exists
  const query = encodeURIComponent(
    `name = '${CHRONO_FOLDER_NAME}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`
  );
  
  const searchRes = await fetch(
    `https://www.googleapis.com/drive/v3/files?q=${query}&fields=files(id,name)`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  );

  if (!searchRes.ok) {
    const errorText = await searchRes.text();
    throw new Error(`Failed to query Google Drive folder: ${searchRes.statusText} (${errorText})`);
  }

  const searchData = await searchRes.json();
  if (searchData.files && searchData.files.length > 0) {
    return searchData.files[0].id;
  }

  // Create new folder
  const createRes = await fetch('https://www.googleapis.com/drive/v3/files', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: CHRONO_FOLDER_NAME,
      mimeType: 'application/vnd.google-apps.folder',
      description: 'Archived historical portraits and temporal photo booth plates created by Chrono-Lens.',
    }),
  });

  if (!createRes.ok) {
    const errorText = await createRes.text();
    throw new Error(`Failed to create Google Drive folder: ${createRes.statusText} (${errorText})`);
  }

  const newFolder = await createRes.json();
  return newFolder.id;
}

/**
 * Upload an image base64 data URL to Google Drive into the Chrono-Lens folder.
 */
export async function uploadImageToDrive(
  accessToken: string,
  params: {
    fileName: string;
    dataUrl: string;
    description?: string;
    properties?: Record<string, string>;
  }
): Promise<DriveFile> {
  const folderId = await findOrCreateChronoFolder(accessToken);

  // Convert base64 dataUrl to binary Blob
  const commaIndex = params.dataUrl.indexOf(',');
  const base64Data = commaIndex >= 0 ? params.dataUrl.substring(commaIndex + 1) : params.dataUrl;
  const mimeTypeMatch = params.dataUrl.match(/data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+).*,.*/);
  const mimeType = mimeTypeMatch ? mimeTypeMatch[1] : 'image/png';

  const byteCharacters = atob(base64Data);
  const byteArrays = [];
  for (let offset = 0; offset < byteCharacters.length; offset += 512) {
    const slice = byteCharacters.slice(offset, offset + 512);
    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }
    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }
  const fileBlob = new Blob(byteArrays, { type: mimeType });

  // Multipart upload metadata + file content
  const metadata = {
    name: params.fileName,
    description: params.description || 'Historical portrait generated by Chrono-Lens',
    parents: [folderId],
    properties: {
      app: 'chrono-lens',
      ...params.properties,
    },
  };

  const boundary = '-------ChronoLensBoundary' + Math.random().toString(36).substring(2);
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const metadataBlob = new Blob([
    delimiter,
    'Content-Type: application/json; charset=UTF-8\r\n\r\n',
    JSON.stringify(metadata),
    delimiter,
    `Content-Type: ${mimeType}\r\n\r\n`,
  ]);

  const closeBlob = new Blob([closeDelimiter]);

  const multipartBody = new Blob([metadataBlob, fileBlob, closeBlob]);

  const uploadRes = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink,webContentLink,thumbnailLink,createdTime,size,description,properties',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: multipartBody,
    }
  );

  if (!uploadRes.ok) {
    const errorText = await uploadRes.text();
    throw new Error(`Google Drive upload failed: ${uploadRes.statusText} (${errorText})`);
  }

  return await uploadRes.json();
}

/**
 * List files stored inside the Chrono-Lens Google Drive folder or matching search.
 */
export async function listChronoDriveFiles(
  accessToken: string,
  searchTerm?: string
): Promise<DriveFile[]> {
  try {
    const folderId = await findOrCreateChronoFolder(accessToken);
    
    let query = `'${folderId}' in parents and trashed = false`;
    if (searchTerm && searchTerm.trim()) {
      const sanitized = searchTerm.replace(/'/g, "\\'");
      query += ` and (name contains '${sanitized}' or description contains '${sanitized}')`;
    }

    const fields = 'files(id,name,mimeType,webViewLink,webContentLink,thumbnailLink,createdTime,modifiedTime,size,description,properties,iconLink)';
    const encodedQuery = encodeURIComponent(query);
    
    const res = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=${encodedQuery}&fields=${encodeURIComponent(fields)}&orderBy=createdTime desc&pageSize=50`,
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Failed to list Google Drive files: ${res.statusText} (${err})`);
    }

    const data = await res.json();
    return data.files || [];
  } catch (err: any) {
    console.error('Error listing Drive files:', err);
    throw err;
  }
}

/**
 * Delete a file from Google Drive (Requires user confirmation before invoking).
 */
export async function deleteDriveFile(accessToken: string, fileId: string): Promise<void> {
  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}`, {
    method: 'DELETE',
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!res.ok && res.status !== 204 && res.status !== 404) {
    const err = await res.text();
    throw new Error(`Failed to delete file from Google Drive: ${res.statusText} (${err})`);
  }
}

/**
 * Fetch Drive user profile & storage quota information.
 */
export async function getDriveStorageInfo(accessToken: string): Promise<DriveStorageQuota> {
  const res = await fetch(
    'https://www.googleapis.com/drive/v3/about?fields=storageQuota,user',
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  );

  if (!res.ok) {
    return {};
  }

  const data = await res.json();
  return {
    limit: data.storageQuota?.limit,
    usage: data.storageQuota?.usage,
    usageInDrive: data.storageQuota?.usageInDrive,
    usageInDriveTrash: data.storageQuota?.usageInDriveTrash,
    userName: data.user?.displayName,
    userEmail: data.user?.emailAddress,
    userPhoto: data.user?.photoLink,
  };
}

/**
 * Fetch image file binary from Drive and convert to base64 data URL
 */
export async function downloadDriveFileAsDataUrl(
  accessToken: string,
  fileId: string,
  mimeType: string = 'image/png'
): Promise<string> {
  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!res.ok) {
    throw new Error(`Failed to download file from Google Drive: ${res.statusText}`);
  }

  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
